# Generated by Django 6.0.7 on 2026-07-26 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='link_url',
            field=models.CharField(blank=True, help_text='Where clicking the banner goes. Examples: /deals/electronics for a category sellout page, /products for the shop page, or a full https:// URL. Use the quick-fill picker below to generate a deals link without typing the slug.', max_length=500),
        ),
    ]
