# Generated by Django 6.0.7 on 2026-07-26 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_discount_percent'),
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'stock_quantity', '-created_at'], name='product_browse_idx'),
        ),
    ]
