# Generated by Django 6.0.7 on 2026-07-29 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='seller-logos/'),
        ),
    ]
